/* 
 * This is not a list of *all* cps es programs -- this is just a list of
 * the CPS ES Programs that the requirement functions refer to.
 * */

// purely ES programs
// --------------------
export const BRADWELL_ES_PROGRAM = "609806-Open Enrollment";
export const CARTER_ES_PROGRAM = "609844-Open Enrollment";
export const CASALS_ES_PROGRAM = "610021-Open Enrollment";
export const CHALMERS_ES_PROGRAM = "609851-Open Enrollment";
export const CURTIS_ES_PROGRAM = "609900-Open Enrollment";
export const DENEEN_ES_PROGRAM = "609883-Open Enrollment";
export const DEWEY_ES_PROGRAM = "609885-Magnet Cluster";
export const DULLES_ES_PROGRAM = "610263-Open Enrollment";
export const DVORAK_ES_PROGRAM = "610254-Magnet Cluster";
export const FULLER_ES_PROGRAM = "609928-Open Enrollment";
export const GRESHAM_ES_PROGRAM = "609955-Open Enrollment";
export const HARVARD_ES_PROGRAM = "609971-Open Enrollment";
export const HERZL_ES_PROGRAM = "609991-Open Enrollment";
export const HOWE_ES_PROGRAM = "610000-Open Enrollment";
export const JOHNSON_ES_PROGRAM = "610274-Open Enrollment";
export const LEWIS_ES_PROGRAM = "610036-Open Enrollment";
export const MARQUETTE_ES_PROGRAM = "610053-Magnet Cluster";
export const MCNAIR_ES_PROGRAM = "610282-Open Enrollment";
export const MORTON_ES_PROGRAM = "610257-Open Enrollment";
export const NATIONAL_TEACHERS_ACADEMY_ES_PROGRAM = "610231-Open Enrollment";
export const OKEEFFE_ES_PROGRAM = "610103-Open Enrollment";
export const PICCOLO_ES_PROGRAM = "610106-Open Enrollment";
export const SHERMAN_ES_PROGRAM = "610172-Open Enrollment";
export const STAGG_ES_PROGRAM = "610339-Open Enrollment";
export const TARKINGTON_ES_PROGRAM = "610396-Open Enrollment";
export const CHICAGO_ACADEMY_ES_PROGRAM = "610248-Open Enrollment";
export const BRENNEMANN_ES_PROGRAM = "610242-Magnet Cluster";
export const COURTENAY_ES_PROGRAM = "610355-Open Enrollment";
export const MCCUTCHEON_ES_PROGRAM = "610269-Open Enrollment";
export const CARNEGIE_MAGNET_CLUSTER_ES_PROGRAM = "609837-Magnet Cluster";
export const CARNEGIE_REGIONAL_GIFTED_CENTER_ES_PROGRAM = "609837-Regional Gifted Center";
export const ALCOTT_ES_PROGRAM = "609774-Open Enrollment";
export const BOONE_ES_PROGRAM = "609804-Magnet Cluster";
export const FIELD_ES_PROGRAM = "609918-Open Enrollment";
export const GALE_ES_PROGRAM = "609933-Open Enrollment";
export const HAYT_ES_PROGRAM = "609976-Open Enrollment";
export const JORDAN_ES_PROGRAM = "609865-Open Enrollment";
export const KILMER_ES_PROGRAM = "610022-Open Enrollment";
export const MCPHERSON_ES_PROGRAM = "610070-Magnet Cluster";
export const WEST_RIDGE_ES_PROGRAM = "610542-Open Enrollment";
export const CALMECA_ES_PROGRAM = "610353-Open Enrollment";
export const COOPER_ES_PROGRAM = "609867-Open Enrollment";
export const AUDUBON_ES_PROGRAM = "609782-Magnet Cluster";
export const BELL_OPEN_ENROLLMENT_ES_PROGRAM = "609799-Open Enrollment";
export const BELL_REGIONAL_GIFTED_CENTER_ES_PROGRAM = "609799-Regional Gifted Center";
export const BLAINE_ES_PROGRAM = "609803-Magnet Cluster";
export const BUDLONG_ES_PROGRAM = "609817-Open Enrollment";
export const BURLEY_ES_PROGRAM = "609820-Magnet Cluster";
export const CHAPPELL_ES_PROGRAM = "609852-Magnet Cluster";
export const COONLEY_OPEN_ENROLLMENT_ES_PROGRAM = "609866-Open Enrollment";
export const COONLEY_REGIONAL_GIFTED_CENTER_ES_PROGRAM = "609866-Regional Gifted Center";
export const GREELEY_MAGNET_CLUSTER_ES_PROGRAM = "609850-Magnet Cluster";
export const GREELEY_REGIONAL_GIFTD_CENTER_FOR_ELS_ES_PROGRAM = "609850-Regional Gifted Center for English Learners";
export const HAMILTON_ES_PROGRAM = "609963-Magnet Cluster";
export const HAWTHORNE_ES_PROGRAM = "609974-Citywide Magnet";
export const INTER_AMERICAN_ES_PROGRAM = "610078-Citywide Magnet";
export const JAHN_ES_PROGRAM = "610010-Magnet Cluster";
export const JAMIESON_ES_PROGRAM = "610011-Open Enrollment";
export const NETTELHORST_ES_PROGRAM = "610094-Magnet Cluster";
export const RAVENSWOOD_ES_PROGRAM = "610141-Magnet Cluster";
export const WATERS_ES_PROGRAM = "610220-Magnet Cluster";

// joint HS / ES programs
// -----------------------
export const FOUNDATIONS_COLLEGE_PREP_JOINT_ES_HS_PROGRAM = "400171-1";
export const CHICAGO_VIRTUAL_CHARTER_JOINT_ES_HS_PROGRAM = "400036-110";
export const CHICAGO_VIRTUAL_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM = "400036-1";
export const CICS_LONGWOOD_CHARTER_JOINT_ES_HS_PROGRAM = "400033-110";
export const CICS_LONGWOOD_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM = "400033-1";
export const CHICAGO_MATH_AND_SCIENCE_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM = "400035-1";
export const U_OF_C_WOODLAWN_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM = "400077-1";
export const CHICAGO_COLLEGIATE_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM = "400161-1";
export const CICS_CHICAGOQUEST_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM = "400113-1";

// Academic Centers (ES Program in HS school)
// ------------------------------------------
export const TAFT_ACADEMIC_CENTER_PROGRAM = "609734-Academic Center";
export const MORGAN_PARK_ACADEMIC_CENTER_PROGRAM = "609725-Academic Center";
export const KENWOOD_ACADEMIC_CENTER_PROGRAM = "609746-Academic Center";


// Groups of programs
// ============================================
export const CARNEGIE_ES_PROGRAMS: string[] = [
  CARNEGIE_REGIONAL_GIFTED_CENTER_ES_PROGRAM,
  CARNEGIE_MAGNET_CLUSTER_ES_PROGRAM
];

export const CPS_JOINT_ES_AND_HS_PROGRAM_IDS: string[] = [
  FOUNDATIONS_COLLEGE_PREP_JOINT_ES_HS_PROGRAM,
  CHICAGO_VIRTUAL_CHARTER_JOINT_ES_HS_PROGRAM,
  CHICAGO_VIRTUAL_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM,
  CICS_LONGWOOD_CHARTER_JOINT_ES_HS_PROGRAM,
  CICS_LONGWOOD_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM,
  U_OF_C_WOODLAWN_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM,
  CHICAGO_MATH_AND_SCIENCE_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM,
  CHICAGO_COLLEGIATE_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM,
  CICS_CHICAGOQUEST_GENERAL_EDUCATION_JOINT_ES_HS_PROGRAM,
];

export const GROW_COMMUNITY_SCHOOL_ES_PROGRAMS: string[] = [
  AUDUBON_ES_PROGRAM,
  BELL_OPEN_ENROLLMENT_ES_PROGRAM,
  BELL_REGIONAL_GIFTED_CENTER_ES_PROGRAM,
  BLAINE_ES_PROGRAM,
  BUDLONG_ES_PROGRAM,
  BURLEY_ES_PROGRAM,
  CHAPPELL_ES_PROGRAM,
  COONLEY_REGIONAL_GIFTED_CENTER_ES_PROGRAM,
  COONLEY_OPEN_ENROLLMENT_ES_PROGRAM,
  GREELEY_REGIONAL_GIFTD_CENTER_FOR_ELS_ES_PROGRAM,
  GREELEY_MAGNET_CLUSTER_ES_PROGRAM,
  HAMILTON_ES_PROGRAM,
  HAWTHORNE_ES_PROGRAM,
  INTER_AMERICAN_ES_PROGRAM,
  JAHN_ES_PROGRAM,
  JAMIESON_ES_PROGRAM,
  MCPHERSON_ES_PROGRAM,
  NETTELHORST_ES_PROGRAM,
  RAVENSWOOD_ES_PROGRAM,
  WATERS_ES_PROGRAM
];

export const AUSL_ES_PROGRAMS: string[] = [
  BRADWELL_ES_PROGRAM,
  CARTER_ES_PROGRAM,
  CASALS_ES_PROGRAM,
  CHALMERS_ES_PROGRAM,
  CURTIS_ES_PROGRAM,
  DENEEN_ES_PROGRAM,
  DEWEY_ES_PROGRAM,
  DULLES_ES_PROGRAM,
  DVORAK_ES_PROGRAM,
  FULLER_ES_PROGRAM,
  GRESHAM_ES_PROGRAM,
  HARVARD_ES_PROGRAM,
  HERZL_ES_PROGRAM,
  HOWE_ES_PROGRAM,
  JOHNSON_ES_PROGRAM,
  LEWIS_ES_PROGRAM,
  MARQUETTE_ES_PROGRAM,
  MCNAIR_ES_PROGRAM,
  MORTON_ES_PROGRAM,
  NATIONAL_TEACHERS_ACADEMY_ES_PROGRAM,
  OKEEFFE_ES_PROGRAM,
  PICCOLO_ES_PROGRAM,
  SHERMAN_ES_PROGRAM,
  STAGG_ES_PROGRAM,
  TARKINGTON_ES_PROGRAM,
  CHICAGO_ACADEMY_ES_PROGRAM,
];


